# Goal: In this workflow, we will validate the indentation, syntax of our python code.

name: python-linter

on:
  push: 
    paths:
      - *.py

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code clone
        uses: actions/checkout@v7
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          
      - name: Install linter
        run: pip install ruff
        
      - name: Run linter
        run: ruff check .

